### PR TITLE
[CDF-20716] Replace environments.yaml with config.[envname].yaml

### PR DESCRIPTION
**Pull request by doctrino**
# Description
Changed how `config.yaml` are generated.

* Calling `cdf-tk init` creates one `config.[env].yaml` per environment defined in `cognite_modules/default.environments.yaml`
* All files prefixed with`default` are not copied when calling `cdf-tk init`. The default files are instead used to setup the `.config[env].yaml . 
* Introducing `_system.yaml` to hold packages and cdf-tk version.
* The `cdf_tk.templates` module started to become hard to navigate, so I turned it into a package.
* Fixed issues with disappearing comments when generating the `config.env.yaml` 

## Checklist

- [ ] Tests added/updated.
- [ ] Run Demo Job Locally.
- [ ] Documentation updated.
- [ ] Changelogs updated in [CHANGELOG.cdf-tk.md](https://github.com/cognitedata/cdf-project-templates/blob/main/CHANGELOG.cdf-tk.md).
- [ ] Template changelogs updated in [CHANGELOG.templates.md](https://github.com/cognitedata/cdf-project-templates/blob/main/CHANGELOG.templates.md).
- [ ] Version bumped.
  [_version.py](https://github.com/cognitedata/cdf-project-templates/blob/main/cognite/cognite_toolkit/_version.py) and
  [pyproject.toml](https://github.com/cognitedata/cdf-project-templates/blob/main/pyproject.toml) per [semantic versioning](https://semver.org/).

### CODE REVIEW

**Comment by ronpal** [comment]
when running build, the warning says 

> WARNING: Found the following warnings in config.yaml

Would be great to have {env}.config.yaml in the message.

**Comment by ronpal** [comment]
Tiniest of readability improvement (I'm open to be challenged on this):

By changing the pattern to config.[env].yaml, the files are alphabetically grouped together without global.yaml inbetween


Screenshot 2024-01-24 at 10 23 47
Screenshot 2024-01-24 at 10 24 51

**Comment by ronpal** [comment]
The README.md in cognite_toolkit needs a refresh:

> Check into Git all the files in this directory, but do not touch the modules
> prefixed with `cdf_*`, only add config.yaml files to the root of each module
> (alongside `default.config.yaml`) to override variables.  You can copy modules
> and build your own modules in the `local_modules` directory. Remember to add the modules
> you want to deploy to the environment you are using in `local.yaml`.
> 
> You can do `cdf-tk init --upgrade` in this directory to upgrade all the `cdf_*` modules to the
> latest version. Your `config.yaml` files will not be touched.

**Comment by ronpal** [comment]
Another structure/usability point: 

We currently have

```
environment:
  name: dev
  project: <customer>-dev
  type: dev
  deploy:
  - cdf_demo_infield
  - cdf_oid_example_data

modules:
  cognite_modules:
    ...
    common:
      ...
    examples:
      cdf_apm_simple_data_model:
```

The link between the items in `deploy` and the modules is unclear. If packages still is a concept, it is hidden from the user. And so it becomes difficult to know which modules that need attention and which can be ignored.

**Comment by ronpal** [comment]
> Another structure/usability point:
> 
> We currently have
> 
> ```
> environment:
>   name: dev
>   project: <customer>-dev
>   type: dev
>   deploy:
>   - cdf_demo_infield
>   - cdf_oid_example_data
> 
> modules:
>   cognite_modules:
>     ...
>     common:
>       ...
>     examples:
>       cdf_apm_simple_data_model:
> ```
> 
> The link between the items in `deploy` and the modules is unclear. If packages still is a concept, it is hidden from the user. And so it becomes difficult to know which modules that need attention and which can be ignored.

**Comment by doctrino** [comment]
> items in `deploy` and the modules is unclear. If packages still is a concept, it is hidden from the user. And so it becomes difficult to know which modules that need attention and which can be ignored.

Suggest we rename the `deploy` key to `selected_modules_and_packages`

**Comment by doctrino** [comment]
> The README.md in cognite_toolkit needs a refresh:
> 
> > Check into Git all the files in this directory, but do not touch the modules
> > prefixed with `cdf_*`, only add config.yaml files to the root of each module
> > (alongside `default.config.yaml`) to override variables.  You can copy modules
> > and build your own modules in the `local_modules` directory. Remember to add the modules
> > you want to deploy to the environment you are using in `local.yaml`.
> > You can do `cdf-tk init --upgrade` in this directory to upgrade all the `cdf_*` modules to the
> > latest version. Your `config.yaml` files will not be touched.

Saving docs and migration until you and Greger agree on the new format.

**Comment by gregertw** [comment]
> > The README.md in cognite_toolkit needs a refresh:
> > > Check into Git all the files in this directory, but do not touch the modules
> > > prefixed with `cdf_*`, only add config.yaml files to the root of each module
> > > (alongside `default.config.yaml`) to override variables.  You can copy modules
> > > and build your own modules in the `local_modules` directory. Remember to add the modules
> > > you want to deploy to the environment you are using in `local.yaml`.
> > > You can do `cdf-tk init --upgrade` in this directory to upgrade all the `cdf_*` modules to the
> > > latest version. Your `config.yaml` files will not be touched.
> 
> Saving docs and migration until you and Greger agree on the new format.

We should review all the docs (more readmes and comments in files), including developer.cognite.com

**Review by gregertw — COMMENTED** [review]
I'm not comfortable with global.yaml and the packages. I thought we agreed that we would not make packages available to users, but reserve packages for contributors. 
I also think we should do a bit of quick user testing here now that we have something working. We are doing a substantial change, so this should get feedback so we are sure we are gong in the right direction with the details.

**Review by gregertw — APPROVED** [review]

**Pull request merged**
